version: '3.4'

networks:
  conversor-moedas-network:
    driver: bridge 

services:
    
  conversormoedas.api:
    build:
      context: .
      dockerfile: ConversorMoedas.Api/Dockerfile
    networks:
      - conversor-moedas-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    networks:
      - conversor-moedas-network
